from tkinter import *
from tkinter import messagebox
import customtkinter
from customtkinter import *
from PIL import Image


# Modes: "System" (standard), "Dark", "Light"
customtkinter.set_appearance_mode("dark")
# Themes: "blue" (standard), "green", "dark-blue"
customtkinter.set_default_color_theme("blue")

class MyShop(customtkinter.CTk):    
    def __init__(self):
        super().__init__()
        
        # Configure window
        self.title("MY Shop")
        self.geometry(f"{700}x{700}")
        self.resizable(False, False)        
        
        # Create search panel
        search_panel = customtkinter.CTkFrame(self, bg_color="grey30", width=470, height=50)
        search_panel.place(x=5, y=5)
        # Create main panel
        main_panel = customtkinter.CTkFrame(self, bg_color="grey30", width=470, height=630)
        main_panel.place(x=5, y=65)
        # Create profile panel
        profile_panel = customtkinter.CTkScrollableFrame(self, bg_color="grey30", width=200, height=690)
        profile_panel.place(x=490, y=5)
        
        #images
        search_icon = customtkinter.CTkImage(light_image=Image.open("Images\Search_Icon.png"), size=(35, 35))
        prof_pic = customtkinter.CTkImage(light_image=Image.open("Images\Default_Profile.png"), size=(140, 160))
        credit_card = customtkinter.CTkImage(light_image=Image.open("Images\Credit_Card.png"), size=(65, 65))
        iphone = customtkinter.CTkImage(light_image=Image.open("Images\iphone14pro.png"), size=(90, 90))
        iphone14 = customtkinter.CTkImage(light_image=Image.open("Images\iphone14pro.png"), size=(300, 350))
        graphics_card = customtkinter.CTkImage(light_image=Image.open("Images\GraphicsCard.png"), size=(90, 90))
        gc = customtkinter.CTkImage(light_image=Image.open("Images\GraphicsCard.png"), size=(300, 350))
        lawn_mower = customtkinter.CTkImage(light_image=Image.open("Images\LawnMower.jpg"), size=(90, 90))
        lm = customtkinter.CTkImage(light_image=Image.open("Images\LawnMower.jpg"), size=(300, 350))
        shopping_cart = customtkinter.CTkImage(light_image=Image.open("Images\ShoppingCart.png"), size=(60, 60))
        hp_laptop = customtkinter.CTkImage(light_image=Image.open("Images\HPLaptop.jpg"), size=(190, 260))
        lg_tv = customtkinter.CTkImage(light_image=Image.open("Images\LGTV.jpg"), size=(190, 260))
        rtx4080 = customtkinter.CTkImage(light_image=Image.open("Images\RTX4080.png"), size=(190, 260))
        xiaomi = customtkinter.CTkImage(light_image=Image.open("Images\Xiaomi_Redmi_Note10.jpg"), size=(190, 260))
        dress = customtkinter.CTkImage(light_image=Image.open("Images\Dress.jpg"), size=(190, 260))
        jeans = customtkinter.CTkImage(light_image=Image.open("Images\Jeans.jpg"), size=(190, 260))
        tshirt = customtkinter.CTkImage(light_image=Image.open("Images\polo.jpg"), size=(190, 260))
        shoes = customtkinter.CTkImage(light_image=Image.open("Images\Shoes.png"), size=(190, 260))
        chair = customtkinter.CTkImage(light_image=Image.open("Images\Chair.jpg"), size=(190, 260))
        pots_pack = customtkinter.CTkImage(light_image=Image.open("Images\Planting pots.jpg"), size=(190, 260))
        plates = customtkinter.CTkImage(light_image=Image.open("Images\plates.jpg"), size=(190, 260))
        toolcase = customtkinter.CTkImage(light_image=Image.open("Images\Toolcase.jpg"), size=(190, 260))
        canvas = customtkinter.CTkImage(light_image=Image.open("Images\Canvas.jpg"), size=(190, 260))
        climbing_gear = customtkinter.CTkImage(light_image=Image.open("Images\Climbing_Gear.jpg"), size=(190, 260))
        guitar = customtkinter.CTkImage(light_image=Image.open("Images\elec_guitar.jpg"), size=(190, 260))
        ucl_ball = customtkinter.CTkImage(light_image=Image.open("Images\Ball.jpg"), size=(190, 260))
        
        # Create search bar widget
        searchcbar = customtkinter.CTkEntry(search_panel, placeholder_text="Search...", width=410, height=45)
        searchcbar.place(x=5, y=5)
        search_button = customtkinter.CTkButton(search_panel, text="", image=search_icon, fg_color='light green', cursor="hand2", width=35, height=45, corner_radius=5)
        search_button.place(x=420, y=5)
        
        # Main menu widgets
        submit_button = customtkinter.CTkButton(main_panel, fg_color="light green", cursor="hand2")
        cancel_button = customtkinter.CTkButton(main_panel, fg_color="light green", cursor="hand2")
        product1 = customtkinter.CTkButton(main_panel, text="", image=hp_laptop, fg_color="grey30", cursor="hand2", height=270, width=200)
        product2 = customtkinter.CTkButton(main_panel, text="", image=lg_tv, fg_color="grey30", cursor="hand2", height=270, width=200)
        product3 = customtkinter.CTkButton(main_panel, text="", image=rtx4080, fg_color="grey30", cursor="hand2", height=270, width=200)
        product4 = customtkinter.CTkButton(main_panel, text="", image=xiaomi, fg_color="grey30", cursor="hand2", height=270, width=200)
        product5 = customtkinter.CTkButton(main_panel, text="", image=dress, fg_color="grey30", cursor="hand2", height=270, width=200)
        product6 = customtkinter.CTkButton(main_panel, text="", image=jeans, fg_color="grey30", cursor="hand2", height=270, width=200)
        product7 = customtkinter.CTkButton(main_panel, text="", image=tshirt, fg_color="grey30", cursor="hand2", height=270, width=200)
        product8 = customtkinter.CTkButton(main_panel, text="", image=shoes, fg_color="grey30", cursor="hand2", height=270, width=200)
        product9 = customtkinter.CTkButton(main_panel, text="", image=chair, fg_color="grey30", cursor="hand2", height=270, width=200)
        product10 = customtkinter.CTkButton(main_panel, text="", image=pots_pack, fg_color="grey30", cursor="hand2", height=270, width=200)
        product11 = customtkinter.CTkButton(main_panel, text="", image=plates, fg_color="grey30", cursor="hand2", height=270, width=200)
        product12 = customtkinter.CTkButton(main_panel, text="", image=toolcase, fg_color="grey30", cursor="hand2", height=270, width=200)
        product13 = customtkinter.CTkButton(main_panel, text="", image=canvas, fg_color="grey30", cursor="hand2", height=270, width=200)
        product14 = customtkinter.CTkButton(main_panel, text="", image=climbing_gear, fg_color="grey30", cursor="hand2", height=270, width=200)
        product15 = customtkinter.CTkButton(main_panel, text="", image=guitar, fg_color="grey30", cursor="hand2", height=270, width=200)
        product16 = customtkinter.CTkButton(main_panel, text="", image=ucl_ball, fg_color="grey30", cursor="hand2", height=270, width=200)
        
        # Profile widgets
        def card_manager():
            def show_cards():
                card_numberLB.place_forget()
                card_number.place_forget()
                ownerLB.place_forget()
                owner.place_forget()
                cvvLB.place_forget()
                cvv.place_forget()
                expdateLB.place_forget()
                expdate.place_forget()
                save_card.place_forget()
                my_cards.place_forget()
                
                cards_list = Listbox(popup, font=('Arial',18), background='grey20', width=30, height=12)
                cards_list.place(x=4, y=10)
                
                def back_to_cards():
                    cards_list.place_forget()
                    back_button.place_forget()
                    card_numberLB = customtkinter.CTkLabel(popup, text="Card Number", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
                    card_number = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=380)
                    ownerLB = customtkinter.CTkLabel(popup, text="Owner", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
                    owner = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=380)
                    cvvLB = customtkinter.CTkLabel(popup, text="CVV", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
                    cvv = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=100)
                    expdateLB = customtkinter.CTkLabel(popup, text="Exparation Date", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
                    expdate = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=150)
                    save_card = customtkinter.CTkButton(popup, text="Save Card", font=('Arial', 18, "bold"), text_color="grey30", fg_color="light green", cursor="hand2", height=30, width=40)
                    my_cards = customtkinter.CTkButton(popup, text="My Cards", font=('Arial', 40, "bold"), text_color="grey30", fg_color="light green", cursor="hand2", height=80, width=300, command=show_cards)
            
                    card_numberLB.place(x=5, y=5)
                    card_number.place(x=5, y=40)
                    ownerLB.place(x=5, y=80)
                    owner.place(x=5, y=115)
                    cvvLB.place(x=5, y=155)
                    cvv.place(x=5, y=190)
                    expdateLB.place(x=120, y=155)
                    expdate.place(x=120, y=190)
                    save_card.place(x=280, y=192)
                    my_cards.place(x=50, y=270)
                
                back_button = customtkinter.CTkButton(popup, text="Back", font=('Arial', 18, "bold"), text_color="grey30", fg_color="light green", cursor="hand2", height=30, width=40, command=back_to_cards)
                back_button.place(x=180, y=360)
                
            popup = CTkToplevel()
            popup.title("Card Manager")
            popup.geometry("400x400+1000+250")
            popup.resizable(False, False)
            card_numberLB = customtkinter.CTkLabel(popup, text="Card Number", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
            card_number = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=380)
            ownerLB = customtkinter.CTkLabel(popup, text="Owner", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
            owner = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=380)
            cvvLB = customtkinter.CTkLabel(popup, text="CVV", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
            cvv = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=100)
            expdateLB = customtkinter.CTkLabel(popup, text="Exparation Date", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
            expdate = customtkinter.CTkTextbox(popup, font=('Arial', 16), fg_color="grey30", height=30, width=150)
            save_card = customtkinter.CTkButton(popup, text="Save Card", font=('Arial', 18, "bold"), text_color="grey30", fg_color="light green", cursor="hand2", height=30, width=40)
            my_cards = customtkinter.CTkButton(popup, text="My Cards", font=('Arial', 40, "bold"), text_color="grey30", fg_color="light green", cursor="hand2", height=80, width=300, command=show_cards)
            
            card_numberLB.place(x=5, y=5)
            card_number.place(x=5, y=40)
            ownerLB.place(x=5, y=80)
            owner.place(x=5, y=115)
            cvvLB.place(x=5, y=155)
            cvv.place(x=5, y=190)
            expdateLB.place(x=120, y=155)
            expdate.place(x=120, y=190)
            save_card.place(x=280, y=192)
            my_cards.place(x=50, y=270)
        
        profile_picture = customtkinter.CTkButton(main_panel, text="", image=prof_pic, fg_color="grey30", cursor="hand2", height=170, width=150)
        nameLB = customtkinter.CTkLabel(main_panel, text="Name", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
        name = customtkinter.CTkTextbox(main_panel, font=('Arial', 16), fg_color="grey30", height=30, width=400)
        emailLB = customtkinter.CTkLabel(main_panel, text="Email", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
        email = customtkinter.CTkTextbox(main_panel, font=('Arial', 16), fg_color="grey30", height=30, width=400)
        countryLB = customtkinter.CTkLabel(main_panel, text="Country", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
        country = customtkinter.CTkTextbox(main_panel, font=('Arial', 16), fg_color="grey30", height=30, width=400)
        adressLb = customtkinter.CTkLabel(main_panel, text="Adress", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
        adress = customtkinter.CTkTextbox(main_panel, font=('Arial', 16), fg_color="grey30", height=30, width=400)
        postalcodeLb = customtkinter.CTkLabel(main_panel, text="Postal Code", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
        postalcode = customtkinter.CTkTextbox(main_panel, font=('Arial', 16), fg_color="grey30", height=30, width=400)
        cardsLB = customtkinter.CTkLabel(main_panel, text="Cards", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
        cards = customtkinter.CTkButton(main_panel, text="", image=credit_card, fg_color="light green", cursor="hand2", height=65, width=65, command=card_manager)
        
        # Shop widgets
        def recomended_opener1():
            popup = CTkToplevel()
            popup.title("My Shop")
            popup.geometry("400x500+1100+200")
            popup.resizable(False, False)
            prod_label = customtkinter.CTkLabel(popup, text="", image=iphone14, height=350, width=200)
            product_info = customtkinter.CTkLabel(popup, text="Iphone 14 Pro", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
            product_price = customtkinter.CTkLabel(popup, text="950€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
            add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
            prod_label.place(x=50, y=5)
            product_info.place(x=20, y=370)
            product_price.place(x=300, y=370)
            add_to_cart.place(x=130, y=420)
            
        def recomended_opener2():
            popup = CTkToplevel()
            popup.title("My Shop")
            popup.geometry("400x500+1100+200")
            popup.resizable(False, False)
            prod_label = customtkinter.CTkLabel(popup, text="", image=gc, height=350, width=200)
            product_info = customtkinter.CTkLabel(popup, text="NVIDIA Geforce GTX 3060 6GB", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
            product_price = customtkinter.CTkLabel(popup, text="    360€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
            add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
            prod_label.place(x=50, y=5)
            product_info.place(x=20, y=370)
            product_price.place(x=300, y=370)
            add_to_cart.place(x=130, y=420)
            
        def recomended_opener3():
            popup = CTkToplevel()
            popup.title("My Shop")
            popup.geometry("400x500+1100+200")
            popup.resizable(False, False)
            prod_label = customtkinter.CTkLabel(popup, text="", image=lm, height=350, width=200)
            product_info = customtkinter.CTkLabel(popup, text="40V 21''Self-Propelled Lawn Mower", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
            product_price = customtkinter.CTkLabel(popup, text="350€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
            add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
            prod_label.place(x=50, y=5)
            product_info.place(x=20, y=370)
            product_price.place(x=300, y=400)
            add_to_cart.place(x=130, y=420)
            
        def technology():
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()

            hp = customtkinter.CTkImage(light_image=Image.open("Images\HPLaptop.jpg"), size=(300, 350))
            lg = customtkinter.CTkImage(light_image=Image.open("Images\LGTV.jpg"), size=(300, 350))
            rtx = customtkinter.CTkImage(light_image=Image.open("Images\RTX4080.png"), size=(300, 350))
            redmi = customtkinter.CTkImage(light_image=Image.open("Images\Xiaomi_Redmi_Note10.jpg"), size=(300, 350))

            def laptop_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=hp, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="HP 15s-eq2037nv R3-5300U", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="450€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=400)
                add_to_cart.place(x=130, y=420)
                
            def tv_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=lg, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Τηλεόραση LG LED 32'' Full HD Smart", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="290€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=400)
                add_to_cart.place(x=130, y=420)
                
            def rtx_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=rtx, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="MSI GeForce RTX 4080 16GB GDDR6X", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="1600€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=400)
                add_to_cart.place(x=130, y=420)
            
            def phone_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=redmi, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Xiaomi Redmi Note 10", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="150€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)    
                
            product1.place(x=20, y=20)
            product1.configure(command=laptop_info)
            product2.place(x=260, y=20)
            product2.configure(command=tv_info)
            product3.place(x=20, y=320)
            product3.configure(command=rtx_info)
            product4.place(x=260, y=320)
            product4.configure(command=phone_info)
        
        def fashion():
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()

            w_dress = customtkinter.CTkImage(light_image=Image.open("Images\Dress.jpg"), size=(300, 350))
            m_jeans = customtkinter.CTkImage(light_image=Image.open("Images\Jeans.jpg"), size=(300, 350))
            polo_tshirt = customtkinter.CTkImage(light_image=Image.open("Images\polo.jpg"), size=(300, 350))
            huh_shoes = customtkinter.CTkImage(light_image=Image.open("Images\Shoes.png"), size=(300, 350))

            def dress_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=w_dress, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Black Dress", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="55€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
                
            def jeans_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=m_jeans, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Slim Jeans", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="20€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
                
            def shirt_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=polo_tshirt, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Purple Polo T-Shirt", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="60€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
            
            def shoes_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=huh_shoes, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="WHAT ARE THOOOSE?", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="300€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)

            product5.place(x=20, y=20)
            product5.configure(command=dress_info)
            product6.place(x=260, y=20)
            product6.configure(command=jeans_info)
            product7.place(x=20, y=320)
            product7.configure(command=shirt_info)
            product8.place(x=260, y=320)
            product8.configure(command=shoes_info)
        
        def home_garden():
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()

            chair_i = customtkinter.CTkImage(light_image=Image.open("Images\Chair.jpg"), size=(300, 350))
            pots_pack_i = customtkinter.CTkImage(light_image=Image.open("Images\Planting pots.jpg"), size=(300, 350))
            plates_i = customtkinter.CTkImage(light_image=Image.open("Images\plates.jpg"), size=(300, 350))
            toolcase_i = customtkinter.CTkImage(light_image=Image.open("Images\Toolcase.jpg"), size=(300, 350))
            
            def chair_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=chair_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Desk Chair", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="65€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
                
            def pots_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=pots_pack_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Planting Pots Pack", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="30€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
                
            def plates_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=plates_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Set of Plates", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="15€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
            
            def tools_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=toolcase_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Toolcase", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="45€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
            
            product9.place(x=20, y=20)
            product9.configure(command=chair_info)
            product10.place(x=260, y=20)
            product10.configure(command=pots_info)
            product11.place(x=20, y=320)
            product11.configure(command=plates_info)
            product12.place(x=260, y=320)
            product12.configure(command=tools_info)
        
        def hobbies():
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()
            
            canvas_i = customtkinter.CTkImage(light_image=Image.open("Images\Canvas.jpg"), size=(300, 350))
            climbing_gear_i = customtkinter.CTkImage(light_image=Image.open("Images\Climbing_Gear.jpg"), size=(300, 350))
            guitar_i = customtkinter.CTkImage(light_image=Image.open("Images\elec_guitar.jpg"), size=(300, 350))
            ucl_ball_i = customtkinter.CTkImage(light_image=Image.open("Images\Ball.jpg"), size=(300, 350))
            
            def canvas_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=canvas_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Canvas", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="15€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
                
            def climbing_gear_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=climbing_gear_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Climbing Gear", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="70€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
                
            def guitar_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=guitar_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="Electronic Guitar", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="550€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)
            
            def uclBall_info():
                popup = CTkToplevel()
                popup.title("My Shop")
                popup.geometry("400x500+1100+200")
                popup.resizable(False, False)
                prod_label = customtkinter.CTkLabel(popup, text="", image=ucl_ball_i, height=350, width=200)
                product_info = customtkinter.CTkLabel(popup, text="UCL 2023 Ball", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                product_price = customtkinter.CTkLabel(popup, text="35€", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
                add_to_cart = customtkinter.CTkButton(popup, text="", image=shopping_cart, fg_color="light green", height=70, width=150)
                prod_label.place(x=50, y=5)
                product_info.place(x=20, y=370)
                product_price.place(x=300, y=370)
                add_to_cart.place(x=130, y=420)

            product13.place(x=20, y=20)
            product13.configure(command=canvas_info)
            product14.place(x=260, y=20)
            product14.configure(command=climbing_gear_info)
            product15.place(x=20, y=320)
            product15.configure(command=guitar_info)
            product16.place(x=260, y=320)
            product16.configure(command=uclBall_info)
               
        recomended = customtkinter.CTkLabel(main_panel, text="Recomended", font=('Comic Sans MS', 16, 'bold'), text_color="light green")
        rec_prod1 = customtkinter.CTkButton(main_panel, text="", image=iphone, fg_color="grey30", cursor="hand2", height=100, width=100, command=recomended_opener1)
        rec_prod2 = customtkinter.CTkButton(main_panel, text="", image=graphics_card, fg_color="grey30", cursor="hand2", height=100, width=100, command=recomended_opener2)
        rec_prod3 = customtkinter.CTkButton(main_panel, text="", image=lawn_mower, fg_color="grey30", cursor="hand2", height=100, width=100, command=recomended_opener3)
        blackline = customtkinter.CTkLabel(main_panel, text="", font=('Arial', 2), fg_color="black")
        categories = customtkinter.CTkLabel(main_panel, text="Categories", font=('Comic Sans MS', 20, 'bold'), text_color="light green", height=30, width=180)
        cat1 = customtkinter.CTkButton(main_panel, text="Devices & Technology", font=('Comic Sans MS', 20, 'bold'), fg_color="DeepSkyBlue4", cursor="hand2", height=190, width=200, command=technology)
        cat2 = customtkinter.CTkButton(main_panel, text="Fashion & Clothing", font=('Comic Sans MS', 20, 'bold'), fg_color="medium orchid", cursor="hand2", height=190, width=200, command=fashion)
        cat3 = customtkinter.CTkButton(main_panel, text="Home & Garden", font=('Comic Sans MS', 20, 'bold'), fg_color="SpringGreen4", cursor="hand2", height=190, width=220, command=home_garden) 
        cat4 = customtkinter.CTkButton(main_panel, text="Sports & Hobbies", font=('Comic Sans MS', 20, 'bold'), fg_color="tomato", cursor="hand2", height=190, width=200, command=hobbies) 
        
        #Orders widgets
        order_label = customtkinter.CTkLabel(main_panel, text="Order", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
        orstatus_label = customtkinter.CTkLabel(main_panel, text="Status", font=('Comic Sans MS', 20, 'bold'), text_color="light green")
        orders_catalog = Listbox(main_panel, font=('Arial',18), background='grey20', width=24, height=20)
        status_catalog = Listbox(main_panel, font=('Arial',18), background='grey20', width=8, height=20)
        
        # Help widgets
        assistance = customtkinter.CTkLabel(main_panel, text="Assistance Center", font=('Comic Sans MS', 30, 'bold'), text_color="grey30", bg_color="light green", height=60, width=450)
        reasonLB = customtkinter.CTkLabel(main_panel, text="What is the issue?", font=('Comic Sans MS', 24, 'bold'), text_color="light green", height=60, width=450)
        reason = customtkinter.CTkComboBox(main_panel, values=["About a product", "Problems with a delivery", "Product destroyed or damaged", "Payment issues and refunds"], font=('Comic Sans MS', 20, 'bold'), width=350)
        explanation = customtkinter.CTkTextbox(main_panel, font=('Arial', 20), fg_color="grey30", height=250, width=400)
        
        def open_prof():
            submit_button.place_forget()
            cancel_button.place_forget()
            assistance.place_forget()
            reasonLB.place_forget()
            reason.place_forget()
            explanation.place_forget()
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()
            product1.place_forget()
            product2.place_forget()
            product3.place_forget()
            product4.place_forget()
            product5.place_forget()
            product6.place_forget()
            product7.place_forget()
            product8.place_forget()
            product9.place_forget()
            product10.place_forget()
            product11.place_forget()
            product12.place_forget()
            product13.place_forget()
            product14.place_forget()
            product15.place_forget()
            product16.place_forget()
            order_label.place_forget()
            orstatus_label.place_forget()
            orders_catalog.place_forget()
            status_catalog.place_forget()
            
            profile_picture.place(x=140, y=10)
            nameLB.place(x=35, y=180)
            name.place(x=30, y=210)
            emailLB.place(x=35, y=250)
            email.place(x=30, y=280)
            countryLB.place(x=35, y=320)
            country.place(x=30, y=350)
            adressLb.place(x=35, y=390)
            adress.place(x=30, y=420)
            postalcodeLb.place(x=35, y=460)
            postalcode.place(x=30, y=490)
            cardsLB.place(x=35, y=530)
            cards.place(x=30, y=555)
            submit_button.configure(text="Save changes", font=('Comic Sans MS', 16, 'bold'), text_color="grey30", height=30, width=90)
            submit_button.place(x=350, y=580)
            cancel_button.configure (text="Discard changes", font=('Comic Sans MS', 16, 'bold'), text_color="grey30", height=30, width=90)
            cancel_button.place(x=210, y=580)
        
        def open_orders():
            submit_button.place_forget()
            cancel_button.place_forget()
            profile_picture.place_forget()
            nameLB.place_forget()
            name.place_forget()
            emailLB.place_forget()
            email.place_forget()
            countryLB.place_forget()
            country.place_forget()
            adressLb.place_forget()
            adress.place_forget()
            postalcodeLb.place_forget()
            postalcode.place_forget()
            cardsLB.place_forget()
            cards.place_forget()
            assistance.place_forget()
            reasonLB.place_forget()
            reason.place_forget()
            explanation.place_forget()
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()
            product1.place_forget()
            product2.place_forget()
            product3.place_forget()
            product4.place_forget()
            product5.place_forget()
            product6.place_forget()
            product7.place_forget()
            product8.place_forget()
            product9.place_forget()
            product10.place_forget()
            product11.place_forget()
            product12.place_forget()
            product13.place_forget()
            product14.place_forget()
            product15.place_forget()
            product16.place_forget()
            
            order_label.place(x=10, y=10)
            orstatus_label.place(x=350, y=10)
            blackline.configure(height=600, width=2)
            blackline.place(x=340, y=10)
            orders_catalog.place(x=10, y=50)
            status_catalog.place(x=350, y=50)
            
        def open_shop():
            submit_button.place_forget()
            cancel_button.place_forget()
            profile_picture.place_forget()
            nameLB.place_forget()
            name.place_forget()
            emailLB.place_forget()
            email.place_forget()
            countryLB.place_forget()
            country.place_forget()
            adressLb.place_forget()
            adress.place_forget()
            postalcodeLb.place_forget()
            postalcode.place_forget()
            cardsLB.place_forget()
            cards.place_forget()
            reasonLB.place_forget()
            reason.place_forget()
            explanation.place_forget()
            blackline.place_forget()
            product1.place_forget()
            product2.place_forget()
            product3.place_forget()
            product4.place_forget()
            product5.place_forget()
            product6.place_forget()
            product7.place_forget()
            product8.place_forget()
            product9.place_forget()
            product10.place_forget()
            product11.place_forget()
            product12.place_forget()
            product13.place_forget()
            product14.place_forget()
            product15.place_forget()
            product16.place_forget()
            order_label.place_forget()
            orstatus_label.place_forget()
            orders_catalog.place_forget()
            status_catalog.place_forget() 
        
            recomended.place(x=20, y=5)
            rec_prod1.place(x=50, y=35)
            rec_prod2.place(x=190, y=35)
            rec_prod3.place(x=330, y=35)
            blackline.configure(height=1, width=430)
            blackline.place(x=20, y=145)
            categories.place(x=145, y=150)
            cat1.place(x=20, y=200)
            cat2.place(x=260, y=200)
            cat3.place(x=20, y=420)
            cat4.place(x=260, y=420)
            
        def open_cart():
            submit_button.place_forget()
            cancel_button.place_forget()
            profile_picture.place_forget()
            nameLB.place_forget()
            name.place_forget()
            emailLB.place_forget()
            email.place_forget()
            countryLB.place_forget()
            country.place_forget()
            adressLb.place_forget()
            adress.place_forget()
            postalcodeLb.place_forget()
            postalcode.place_forget()
            cardsLB.place_forget()
            cards.place_forget()
            assistance.place_forget()
            reasonLB.place_forget()
            reason.place_forget()
            explanation.place_forget()
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()
            product1.place_forget()
            product2.place_forget()
            product3.place_forget()
            product4.place_forget()
            product5.place_forget()
            product6.place_forget()
            product7.place_forget()
            product8.place_forget()
            product9.place_forget()
            product10.place_forget()
            product11.place_forget()
            product12.place_forget()
            product13.place_forget()
            product14.place_forget()
            product15.place_forget()
            product16.place_forget()
            order_label.place_forget()
            orstatus_label.place_forget()
            orders_catalog.place_forget()
            status_catalog.place_forget() 
        
        def open_shop_help():
            submit_button.place_forget()
            cancel_button.place_forget()
            profile_picture.place_forget()
            nameLB.place_forget()
            name.place_forget()
            emailLB.place_forget()
            email.place_forget()
            countryLB.place_forget()
            country.place_forget()
            adressLb.place_forget()
            adress.place_forget()
            postalcodeLb.place_forget()
            postalcode.place_forget()
            cardsLB.place_forget()
            cards.place_forget()
            recomended.place_forget()
            rec_prod1.place_forget()
            rec_prod2.place_forget()          
            rec_prod3.place_forget()
            blackline.place_forget()
            categories.place_forget()
            cat1.place_forget()
            cat2.place_forget()
            cat3.place_forget()
            cat4.place_forget()
            product1.place_forget()
            product2.place_forget()
            product3.place_forget()
            product4.place_forget()
            product5.place_forget()
            product6.place_forget()
            product7.place_forget()
            product8.place_forget()
            product9.place_forget()
            product10.place_forget()
            product11.place_forget()
            product12.place_forget()
            product13.place_forget()
            product14.place_forget()
            product15.place_forget()
            product16.place_forget()
            order_label.place_forget()
            orstatus_label.place_forget()
            orders_catalog.place_forget()
            status_catalog.place_forget()
            
            assistance.place(x=10, y=20)
            reasonLB.place(x=10, y=100)
            reason.place(x=60, y=160)
            explanation.place(x=30, y=220)
            submit_button.configure(text="Submit help ticket", font=('Comic Sans MS', 20, 'bold'), text_color="grey30", height=40, width=100)
            submit_button.place(x=130, y=500)
        
        # Create profile widgets
        prof = customtkinter.CTkButton(profile_panel, text="Profile", font=('Comic Sans MS', 27, 'bold'), text_color="grey30", fg_color="light green", cursor="hand2", height=60, width=180, command=open_prof)
        prof.pack(padx=5, pady=5)
        orders = customtkinter.CTkButton(profile_panel, text="My Orders", font=('Comic Sans MS', 27, 'bold'), text_color="grey30", fg_color="light green", cursor="hand2", height=60, width=180, command=open_orders)
        orders.pack(padx=5, pady=20)
        shop_menu = customtkinter.CTkButton(profile_panel, text="Shop", font=('Comic Sans MS', 27, 'bold'), text_color="grey30", fg_color="light green", cursor="hand2", height=60, width=180, command=open_shop)
        shop_menu.pack(padx=5, pady=10)
        cart = customtkinter.CTkButton(profile_panel, text="My Cart", font=('Comic Sans MS', 27, 'bold'), text_color="grey30", fg_color="light green", cursor="hand2", height=60, width=180, command=open_cart)
        cart.pack(padx=5, pady=20)
        shop_help = customtkinter.CTkButton(profile_panel, text="Help", font=('Comic Sans MS', 27, 'bold'), text_color="grey30", fg_color="light green", cursor="hand2", height=60, width=180, command=open_shop_help)
        shop_help.pack(padx=5, pady=260)
        
        
if __name__ == "__main__":
    app = MyShop()
    app.mainloop()